spring:
  cache:
    type: simple
  datasource:
    url: jdbc:mysql://localhost:3306/simops?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
security:
    allowed-origins:
      - '*'
    jwt-secret-key: iQCfwM6Zl12b7T2CjPK3ZFaVFWqoydF1cDnQyb5ed20
    password-encoder: md5

simple-ops:
  admin-password: admin@